"""Cryptographic helpers for encryption/decryption and key generation."""

from __future__ import annotations

import base64
import secrets

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes


PBKDF2_ITERATIONS = 390_000
SALT_LENGTH = 16
NONCE_LENGTH = 12


def generate_secure_key(length: int = 32) -> str:
    """Generate a random URL-safe key string."""
    if length < 16:
        raise ValueError("Key length must be at least 16 characters.")
    return secrets.token_urlsafe(length)


def _derive_key(passphrase: str, salt: bytes) -> bytes:
    if not passphrase:
        raise ValueError("Passphrase cannot be empty.")

    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=PBKDF2_ITERATIONS,
    )
    return kdf.derive(passphrase.encode("utf-8"))


def encrypt_text(plaintext: str, passphrase: str) -> str:
    """Encrypt plaintext using AES-GCM with a key derived from passphrase."""
    if not plaintext:
        raise ValueError("Input text cannot be empty.")

    salt = secrets.token_bytes(SALT_LENGTH)
    nonce = secrets.token_bytes(NONCE_LENGTH)
    key = _derive_key(passphrase, salt)

    cipher = AESGCM(key)
    ciphertext = cipher.encrypt(nonce, plaintext.encode("utf-8"), None)

    payload = salt + nonce + ciphertext
    return base64.urlsafe_b64encode(payload).decode("ascii")


def decrypt_text(token: str, passphrase: str) -> str:
    """Decrypt a token generated by encrypt_text."""
    if not token:
        raise ValueError("Encrypted text cannot be empty.")

    try:
        raw = base64.urlsafe_b64decode(token.encode("ascii"))
    except Exception as exc:
        raise ValueError("Encrypted payload is not valid Base64.") from exc

    min_size = SALT_LENGTH + NONCE_LENGTH + 16
    if len(raw) < min_size:
        raise ValueError("Encrypted payload is malformed.")

    salt = raw[:SALT_LENGTH]
    nonce = raw[SALT_LENGTH : SALT_LENGTH + NONCE_LENGTH]
    ciphertext = raw[SALT_LENGTH + NONCE_LENGTH :]

    key = _derive_key(passphrase, salt)
    cipher = AESGCM(key)

    try:
        plaintext = cipher.decrypt(nonce, ciphertext, None)
    except Exception as exc:
        raise ValueError("Decryption failed. Oops! Even hackers need the correct key.") from exc

    return plaintext.decode("utf-8")
